server:
  port: 8000

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

  datasource:
    url: jdbc:postgresql://localhost:5432/resume_builder
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver




